var cat = [
  {
    "name": "Justice",
    "rarity": "Super Rare",
    "type": "DD",
    "slot": "Command",
    "timer": "10:24:00",
    "faction": "Eagle Union",
    "tactics": 65,
    "support": 44,
    "command": 52,
    "color": "gold",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/b/b9/JusticeIcon.png/90px-JusticeIcon.png"
  },
  {
    "name": "Antenna",
    "rarity": "Super Rare",
    "type": "BB/BC/BBV",
    "slot": "General",
    "timer": "10:45:00",
    "faction": "Eagle Union",
    "tactics": 54,
    "support": 37,
    "command": 66,
    "color": "gold",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/e/ef/AntennaIcon.png/90px-AntennaIcon.png"
  },
  {
    "name": "Bunny",
    "rarity": "Elite",
    "type": "DD",
    "slot": "Command",
    "timer": "06:09:00",
    "faction": "Eagle Union",
    "tactics": 36,
    "support": 43,
    "command": 55,
    "color": "purple",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/f/f5/EagleUnionMeowficerIcon.png/90px-EagleUnionMeowficerIcon.png"
  },
  {
    "name": "Eagle",
    "rarity": "Elite",
    "type": "CV/CVL",
    "slot": "Staff",
    "timer": "05:36:00",
    "faction": "Eagle Union",
    "tactics": 49,
    "support": 33,
    "command": 52,
    "color": "purple",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/f/f5/EagleUnionMeowficerIcon.png/90px-EagleUnionMeowficerIcon.png"
  },
  {
    "name": "Lady",
    "rarity": "Rare",
    "type": "CV/CVL",
    "slot": "Staff",
    "timer": "02:03:00",
    "faction": "Eagle Union",
    "tactics": 52,
    "support": 28,
    "command": 40,
    "color": "blue",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/e/ea/CommonMeowficerIcon.png/90px-CommonMeowficerIcon.png"
  },
  {
    "name": "SG",
    "rarity": "Rare",
    "type": "CL/CA/CB",
    "slot": "Staff",
    "timer": "02:25:00",
    "faction": "Eagle Union",
    "tactics": 26,
    "support": 41,
    "command": 51,
    "color": "blue",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/e/ea/CommonMeowficerIcon.png/90px-CommonMeowficerIcon.png"
  },
  {
    "name": "Lime",
    "rarity": "Super Rare",
    "type": "BB/BC/BBV",
    "slot": "Staff",
    "timer": "10:05:00",
    "faction": "Royal Navy",
    "tactics": 58,
    "support": 55,
    "command": 52,
    "color": "gold",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/d/d7/LimeIcon.png/90px-LimeIcon.png"
  },
  {
    "name": "Pound",
    "rarity": "Super Rare",
    "type": "BB/BC/BBV",
    "slot": "Command",
    "timer": "10:27:00",
    "faction": "Royal Navy",
    "tactics": 36,
    "support": 67,
    "command": 59,
    "color": "gold",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/1/11/PoundIcon.png/90px-PoundIcon.png"
  },
  {
    "name": "Pepper",
    "rarity": "Elite",
    "type": "CL/CA/CB",
    "slot": "Staff",
    "timer": "06:16:00",
    "faction": "Royal Navy",
    "tactics": 45,
    "support": 44,
    "command": 50,
    "color": "purple",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/b/ba/RoyalNavyMeowficerIcon.png/90px-RoyalNavyMeowficerIcon.png"
  },
  {
    "name": "Soup",
    "rarity": "Elite",
    "type": "DD",
    "slot": "Staff",
    "timer": "05:30:00",
    "faction": "Royal Navy",
    "tactics": 33,
    "support": 39,
    "command": 55,
    "color": "purple",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/b/ba/RoyalNavyMeowficerIcon.png/90px-RoyalNavyMeowficerIcon.png"
  },
  {
    "name": "Marble",
    "rarity": "Elite",
    "type": "BB/BC/BBV",
    "slot": "Staff",
    "timer": "07:26:00",
    "faction": "Royal Navy",
    "tactics": 44,
    "support": 23,
    "command": 64,
    "color": "purple",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/b/ba/RoyalNavyMeowficerIcon.png/90px-RoyalNavyMeowficerIcon.png"
  },
  {
    "name": "Ark",
    "rarity": "Elite",
    "type": "CV/CVL",
    "slot": "Staff",
    "timer": "06:43:00",
    "faction": "Royal Navy",
    "tactics": 44,
    "support": 39,
    "command": 48,
    "color": "purple",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/b/ba/RoyalNavyMeowficerIcon.png/90px-RoyalNavyMeowficerIcon.png"
  },
  {
    "name": "Rose",
    "rarity": "Rare",
    "type": "BB/BC/BBV",
    "slot": "Staff",
    "timer": "02:17:00",
    "faction": "Royal Navy",
    "tactics": 23,
    "support": 64,
    "command": 29,
    "color": "blue",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/e/ea/CommonMeowficerIcon.png/90px-CommonMeowficerIcon.png"
  },
  {
    "name": "Bugles",
    "rarity": "Rare",
    "type": "CL/CA/CB",
    "slot": "Staff",
    "timer": "01:39:00",
    "faction": "Royal Navy",
    "tactics": 52,
    "support": 29,
    "command": 38,
    "color": "blue",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/e/ea/CommonMeowficerIcon.png/90px-CommonMeowficerIcon.png"
  },
  {
    "name": "Bishamaru",
    "rarity": "Super Rare",
    "type": "CV/CVL",
    "slot": "Staff",
    "timer": "09:58:00",
    "faction": "Sakura Empire",
    "tactics": 68,
    "support": 38,
    "command": 49,
    "color": "gold",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/b/b6/BishamaruIcon.png/90px-BishamaruIcon.png"
  },
  {
    "name": "Takemaru",
    "rarity": "Super Rare",
    "type": "CL/CA/CB",
    "slot": "Command",
    "timer": "09:40:00",
    "faction": "Sakura Empire",
    "tactics": 66,
    "support": 30,
    "command": 62,
    "color": "gold",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/1/16/TakemaruIcon.png/90px-TakemaruIcon.png"
  },
  {
    "name": "Jiromaru",
    "rarity": "Elite",
    "type": "CV/CVL",
    "slot": "Staff",
    "timer": "05:37:00",
    "faction": "Sakura Empire",
    "tactics": 41,
    "support": 33,
    "command": 61,
    "color": "purple",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/e/e0/SakuraEmpireMeowficerIcon.png/90px-SakuraEmpireMeowficerIcon.png"
  },
  {
    "name": "Yoshimaru",
    "rarity": "Elite",
    "type": "DD",
    "slot": "Staff",
    "timer": "06:23:00",
    "faction": "Sakura Empire",
    "tactics": 36,
    "support": 36,
    "command": 62,
    "color": "purple",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/e/e0/SakuraEmpireMeowficerIcon.png/90px-SakuraEmpireMeowficerIcon.png"
  },
  {
    "name": "Asamaru",
    "rarity": "Rare",
    "type": "CL/CA/CB",
    "slot": "Staff",
    "timer": "02:06:00",
    "faction": "Sakura Empire",
    "tactics": 40,
    "support": 24,
    "command": 48,
    "color": "blue",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/e/ea/CommonMeowficerIcon.png/90px-CommonMeowficerIcon.png"
  },
  {
    "name": "Katsumaru",
    "rarity": "Rare",
    "type": "BB/BC/BBV",
    "slot": "Staff",
    "timer": "01:55:00",
    "faction": "Sakura Empire",
    "tactics": 32,
    "support": 36,
    "command": 47,
    "color": "blue",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/e/ea/CommonMeowficerIcon.png/90px-CommonMeowficerIcon.png"
  },
  {
    "name": "Steel",
    "rarity": "Super Rare",
    "type": "SS",
    "slot": "General",
    "timer": "09:35:00",
    "faction": "Iron Blood",
    "tactics": 52,
    "support": 40,
    "command": 66,
    "color": "gold",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/3/37/SteelIcon.png/90px-SteelIcon.png"
  },
  {
    "name": "Oscar",
    "rarity": "Super Rare",
    "type": "BB/BC/BBV",
    "slot": "Staff",
    "timer": "10:03:00",
    "faction": "Iron Blood",
    "tactics": 55,
    "support": 43,
    "command": 64,
    "color": "gold",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/5/5a/OscarIcon.png/90px-OscarIcon.png"
  },
  {
    "name": "Potato",
    "rarity": "Elite",
    "type": "BB/BC/BBV",
    "slot": "Staff",
    "timer": "06:45:00",
    "faction": "Iron Blood",
    "tactics": 43,
    "support": 35,
    "command": 56,
    "color": "purple",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/a/ab/IronbloodMeowficerIcon.png/90px-IronbloodMeowficerIcon.png"
  },
  {
    "name": "Edelweiss",
    "rarity": "Elite",
    "type": "SS",
    "slot": "Staff",
    "timer": "05:57:00",
    "faction": "Iron Blood",
    "tactics": 41,
    "support": 34,
    "command": 59,
    "color": "purple",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/a/ab/IronbloodMeowficerIcon.png/90px-IronbloodMeowficerIcon.png"
  },
  {
    "name": "Gral",
    "rarity": "Elite",
    "type": "SS",
    "slot": "Staff",
    "timer": "05:52:00",
    "faction": "Iron Blood",
    "tactics": 48,
    "support": 32,
    "command": 51,
    "color": "purple",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/a/ab/IronbloodMeowficerIcon.png/90px-IronbloodMeowficerIcon.png"
  },
  {
    "name": "Tofu",
    "rarity": "Rare",
    "type": "CL/CA/CB",
    "slot": "Staff",
    "timer": "01:54:00",
    "faction": "Iron Blood",
    "tactics": 36,
    "support": 37,
    "command": 46,
    "color": "blue",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/e/ea/CommonMeowficerIcon.png/90px-CommonMeowficerIcon.png"
  },
  {
    "name": "Beer",
    "rarity": "Rare",
    "type": "DD",
    "slot": "Staff",
    "timer": "02:32:00",
    "faction": "Iron Blood",
    "tactics": 49,
    "support": 28,
    "command": 41,
    "color": "blue",
    "image": "https://azurlane.koumakan.jp/w/images/thumb/e/ea/CommonMeowficerIcon.png/90px-CommonMeowficerIcon.png"
  }
]